<<<<<<< HEAD
# Generated by Django 4.2.2 on 2024-01-09 11:02
=======
# Generated by Django 4.2.2 on 2024-01-09 10:57
>>>>>>> 6dfd8e8572edda4ad3568f3629be84484d9f6ee3

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
<<<<<<< HEAD

=======
>>>>>>> 6dfd8e8572edda4ad3568f3629be84484d9f6ee3
    dependencies = [
        ("users", "0002_user_is_verifacated_email_alter_user_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
