# Generated by Django 4.2.2 on 2023-12-28 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="products",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
        migrations.RemoveField(
            model_name="products",
            name="image",
        ),
        migrations.AddField(
            model_name="products",
            name="gender",
            field=models.CharField(
                choices=[("M", "Мужской"), ("F", "Женский"), ("U", "Унисекс")],
                default="U",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="main_image",
            field=models.ImageField(
                default=None, upload_to=products.models.Products.upload_to
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="slug",
            field=models.SlugField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name="products",
            name="stripe_product_price_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="company",
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.CreateModel(
            name="ProductSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size_name", models.CharField(max_length=50)),
                ("bust_size", models.PositiveIntegerField(blank=True, null=True)),
                ("waist_size", models.PositiveIntegerField(blank=True, null=True)),
                ("hip_size", models.PositiveIntegerField(blank=True, null=True)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="products.products",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=products.models.ProductImage.upload_to),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_product_images",
                        to="products.products",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Basket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(default=0)),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.products",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
