# Generated by Django 4.2.2 on 2023-06-29 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_basket"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="products",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
    ]
